class Buku {
  String judul,
    penulis,
    jenis,
    gambar,
    sinopsis;
int halaman;
double rating;

Buku(this.judul, this.penulis, this.jenis,this.gambar, this.halaman, this.rating, this.sinopsis);
}

final List<Buku> bukuu = [
  Buku('Garis Waktu', 'Fiersa Besari', 'Fiksi/Sastra','img/Fiersa_b1.jpg',211 ,5 , 'Pada sebuah garis waktu yang merangkak maju, akan ada saatnya kau bertemu dengan satu orang yang mengubah hidupmu untuk selamanya.\tPada sebuah garis waktu yang merangkak maju, akan ada saatnya kau terbuka dan kehilangan pegangan.\t \tPada sebuah garis waktu yang merangkak maju, akan ada saatnya kau ingin melompat mundur pada titik-titik kenangan tertentu.\tMaka, ikhlaskan saja kalau begitu.\tKarena sesungguhnya,yang lebih menyakitkan dari melepaskan sesuatu adalah berpegangan pada sesuatu yang menyakitimu secara perlahan.'),
  Buku('Konspirasi Alam Semesta', 'Fiersa Besari', 'Fiksi/Sastra','img/Fiersa_b2.jpg',244 ,5 , 'Seperti apakah warna cinta? Apakah merah muda mewakili rekahannya, ataukah kelabu mewakili pecahannya?'),
  Buku('Supernova : Ksatria, Peri, & Bintang Jatuh', 'Dee Lestari', 'Fiksi/Sastra','img/Dee_b1.jpg',342 ,5 , 'Menunaikan ikrar mereka untuk berkarya bersama, pasangan Dimas dan Reuben mulai menulis roman yang diberi judul Kesatria, Putri, dan Bintang Jatuh.\tParalel dengan itu, dalam kehidupan nyata, sebuah kisah cinta terlarang terjalin antara Ferre dan Rana. Hubungan cinta mereka merepresentasikan dinamika yang terjadi antara tokoh Kesatria dan Putri dalam fiksi Dimas dan Reuben.\tTokoh ketiga, Bintang Jatuh, dihadirkan oleh seorang peragawati terkenal bernama Diva, yang memiliki profesi sampingan sebagai pelacur kelas atas.\tTanpa ada yang bisa mengantisipasi, kehadiran sosok bernama Supernova menjadi kunci penentu yang akhirnya merajut kehidupan nyata antara Ferre-Rana-Diva dengan kisah fiksi karya Dimas-Reuben dalam satu dimensi kehidupan yang sama.'),
  Buku('Narnia : The Magicians Nephew', 'C. S. lewis', 'Fantasi','img/Narnia_b1.jpg',280 ,5 , 'Tentukan pilihan, wahai petualang asing, Bunyikan bel, dan hadapi bahaya genting, Atau teruslah penasaran, hingga lenyap kewarasan, Akan apa yang bakal terjadi bila saja kaulakukan. \t Dua anak, Digory dan Polly, telah diperdaya Sihir dan paman Digory yang nyentrik, Paman Andrew. Dia memaksa mereka membuat pilihan yang hasilnya adalah petualangan yang jauh lebih luar biasa daripada mimpi. Mereka menemukan dunia-dunia lain di dalam mata air ajaib, bertemu ratu agung yang juga penyihir kejam, dan tanah kebeliaan yang baru saja dibangkitkan. Mereka membuka pintu menuju tanah Narnia untuk pertama kalinya ...'),
  Buku('Narnia : The Lion,The Witch, and The Wardobe', 'C. S. lewis', 'Fantasi','img/Narnia_b2.jpg',232 ,5 , '"Itu Lemari ajaib. Ada hutan di dalamnya, dan di sana sedang hujan salju! Ayo mari lihat," Kata Lucy memohon.\t\t\tEmpat anak, Peter, Edmund, Susan, dan Lucy, dievakuasi ke desa saat perang. Tapi, tak lama kemudian mereka menemukan diri mereka menghadapi bahaya yang sesungguhnya ketika Lucy masuk ke dunia ajaib Narnia. Musim salju dan Penyihir Putih adalah ancaman terbesar di sana. Hanya keempat anak serta singa agung, Aslan, yang bisa mematahkan kutukan jahat penyihir itu.'),
  Buku('Narnia : The Horse and His Boy', 'C. S. lewis', 'Fantasi','img/Narnia_b3.jpg',312 ,5 , 'Berpacu Menuju Kebebasan\t\tNarnia...\ttanah di mana para kuda bisa berbicara...\tpengkhianatan mengintai...\tdan takdir menanti.\tDalam perjalanan penuh tantangan, empat pelarian bertemu dan bergabung. Meski awalnya mereka hanya berusaha membebaskan diri dari kehidupan yang kejam dan menekan, tak lama kemudian mereka mendapati diri mereka berada di tengah-tengah pertempuran dahsyat. Pertempuran yang akan memutuskan bukan hanya nasib mereka, tapi juga nasib Narnia'),
  Buku('Narnia : Prince Caspian', 'C. S. lewis', 'Fantasi','img/Narnia_b4.jpg',280 ,5 , 'Pangeran mempertahankan takhtanya...\t Narnia... tempat para binatang bicara... tempat pohon-pohon berjalan... tempat perang akan dimulai.\t Hak seorang pangeran atas takhtanya dicabut. Dia mengumpulkan pasukan dan berusaha menyingkirkan raja palsu dari negerinya. Tapi akhirnya, duel mempertahankan kehormatan antara dua prialah yang akan memutuskan nasib seluruh dunia.'),
  Buku('Narnia : The Voyage of the Dawn Treader', 'C. S. lewis', 'Fantasi','img/Narnia_b5.jpg',344 ,5 , 'Petualangan menuju ujung akhir dunia\tNARNIA...\tdi mana naga terbangun...\tdi mana bintang menjejaki bumi...\tdi mana apa pun bisa terjadi.\t\t\tSeorang raja dan beberapa teman seperjalanan yang tidak disangka-sangka memulai pelayaran yang akan membawa mereka ke negeri-negeri tak terjamah. Ketika mereka bergerak kian jauh dan terus menjauh dari perairan yang dikenal, mereka mendapati petualangan ini ternyata lebih luar biasa daripada yang pernah dibayangkan. Ujung akhir dunia hanyalah sebuah permulaan. '),
  Buku('Narnia : The Silver Chair', 'C. S. lewis', 'Fantasi','img/Narnia_b6.jpg',320 ,5 , 'Pangeran Tertawan-Negeri Dalam Kehancuran.\tNarnia, tempat raksasa merusak, tempat kejahatan menimpakan kutukan, tempat sihir jadi penguasa. Melalui bahaya-bahaya luar biasa dan gua-gua dalam nan gelap, tiga sahabat dikirim untuk menyelamatkan seorang pangeran yang tertawan. Tapi misi mereka ke Dunia Bawah membuat mereka berhadapan langsung dengan penyihir yang jauh lebih cantik dan berbahaya daripada yang pernah mereka bayangkan.'),
  Buku('Narnia : The Last Battle', 'C. S. lewis', 'Fantasi','img/Narnia_b7.jpg',280 ,5 , 'Pertempuran terakhir yang terdahsyat Narnia... di mana kebohongan melahirkan ketakutan... di mana kesetiaan diuji... di mana semua harapan seolah sirna. Pada hari-hari terakhir Narnia, tanah itu menghadapi tantangan terbesarnya---bukan dari kekuatan asing di luar melainkan musuh dari dalam. Kebohongan dan pengkhianatan menancapkan kuku, dan hanya sang raja serta sekelompok kecil pengikut setia yang bisa mencegah kehancuran semua yang mereka sayangi dalam kisah terakhir The Chronicles of Narnia.'),
];
